#!/bin/bash
# Author: Evan de la Cruz
# Author: adaylateandadollarshort
# for nodedaddy
#2017-12-09
#this script can be reached at https://goo.gl/BrjeQk

trustystring="trusty"
xenialstring="xenial"

echo "Checking your Linux version..."
thisrelease=$(lsb_release -a)
if test "${thisrelease#*$trustystring}" != "$thisrelease"; then

	echo "Downloading Trusty installer..."
	if [ -f send-masternode-install-1.0.0.5-Ubuntu14 ]; then
		rm -f send-masternode-install-1.0.0.5-Ubuntu14
	fi
	wget --no-cache https://raw.githubusercontent.com/nodedaddy/send-masternode-installer/master/send-masternode-install-1.0.0.5-Ubuntu14
	chmod +x send-masternode-install-1.0.0.5-Ubuntu14
	clear
	echo "Running the installer..."
	echo " "
	./send-masternode-install-1.0.0.5-Ubuntu14
elif test "${thisrelease#*$xenialstring}" != "$thisrelease"; then
	echo "Sorry, the installer currently only supports Ubuntu 14. We are working on a version for Ubuntu Xenial."
else
	echo "Sorry, the installer currently only supports Ubuntu 14."
fi
